size: 30x30
generator:
  Nystrom:
    roomPlacementAttempts: 50
    minRoomSize: 5x5
    maxRoomSize: 10x10
modifiers:
  - BreakPassages:
      amount: 100
      minimumShortcutDistance: 50
  - RemoveDeadends:0.4
  - Emmure
